export enum Achievement {
    PROFILE_COMPLETED = 'PROFILE_COMPLETED',
    FIRST_PROJECT = 'FIRST_PROJECT',
    FIRST_CERTIFICATION = 'FIRST_CERTIFICATION',
    FIRST_SKILL = 'FIRST_SKILL',
    FIRST_LANGUAGE = 'FIRST_LANGUAGE'
  }