import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { roboto } from "@/ui/fonts";
import '@mantine/core/styles.css';
import { createTheme, MantineProvider } from '@mantine/core';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">       
        <body className={roboto.className}>
        <MantineProvider>
            {children}
        </MantineProvider>      
          </body>     
      </html>
    
  );
}
