import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { roboto } from "@/ui/fonts";
import { Header } from "@/components/Header/Header";
import {  Footer } from "@/components/Footer/Footer";
import favicon from './favicon.ico'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Krovit",
  description: "Generated by Krovit",
  icons: {
    icon: '/favicon.ico' , // /public path
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">       
        <body className={inter.className} id="bodyScroll">
            <Header/>
            {children}
            <Footer/>      
          </body>     
      </html>
    
  );
}
